### PR TITLE
Update pornography-hosts

### PR DESCRIPTION
**Pull request by defa02005**

### CODE REVIEW

**Comment by DREADSBAILEY110** [comment]
gh pr checkout 160

**Comment by DREADSBAILEY110** [comment]
Thanks u

**Comment by DREADSBAILEY110** [comment]
[hostfiles-master.zip](https://github.com/Sinfonietta/hostfiles/files/7786505/hostfiles-master.zip)

**Comment by Sinfonietta** [comment]
Thank you @defa02005 sorry for the delay on this.  I am merging this.

**Pull request merged**
