### PR TITLE
Added nsfw.xxx

### PR DESCRIPTION
**Pull request by Bakerbakura**

### CODE REVIEW

**Comment by spirillen** [comment]
Your commit is incomplete: https://mypdns.org/my-privacy-dns/porn-records/-/issues/1777

**Comment by Bakerbakura** [comment]
Hi, it seems the procedure is a little different since I last added records to this project. Could you tell me what still needs to be done here? Especially since the issue in the link you gave has been closed?

**Comment by spirillen** [comment]
> Hi, it seems the procedure is a little different since I last added records to this project.

That I can't tell, I can only tell you that I have found more data and added those into my own project. Next this to well share the knowledge.

> Could you tell me what still needs to be done here? Especially since the issue in the link you gave has been closed?

That is is closed only means it is considered solved and it is still an active for that domain disregard what, the rule is one domain = one issue. (it is related to a long running idea)

But what you are missing is this section https://mypdns.org/my-privacy-dns/porn-records/-/issues/1777#additional-requirements-for-dumb-hosts-files, as this is a hosts file :wink:

-------

I was hoping that had been more clear :unamused: Could you give me a hint to how i could improve my template for making this more clear to others, that this section is to be included for hosts/pi-hole users to folly stop the NSFW contents from this domain?

--------

May I ask how you use this project / list?

**Comment by Sinfonietta** [comment]
Thank you @Bakerbakura I am merging this.

**Pull request merged**
