### PR TITLE
Update snuff-hosts

### PR DESCRIPTION
**Pull request by paxperscientiam**
Serves snuff in addition to porn

### CODE REVIEW

**Comment by spirillen** [comment]
Hey @paxperscientiam can you provide an example of that? I can't seems to find any snuff there...

**Comment by paxperscientiam** [comment]
Hi, @spirillen, yes I can. Please be advised, content could legitimately be deemed Not Safe For Life. `tinyurl.com/w49w3uw`

A warning to anyone else, don't visit this link if you don't want to see terrible violence.

**Comment by Sinfonietta** [comment]
Thank you @paxperscientiam, and sorry for the delay merging this.

**Comment by spirillen** [comment]
That do not looks like a Hollywood production :sob:

**Pull request merged**
