### PR TITLE
For your consideration: added 17 New Adult Hosts; Sorted and Deduplicated File

### PR DESCRIPTION
**Pull request by okrabiblestudy**
Hi

Thank you for creating and maintaining this list.

I have added a few more adult domains to the relevant host file:

```
0.0.0.0 aabj.net
0.0.0.0 www.aabj.net
0.0.0.0 adultboard.net
0.0.0.0 www.adultboard.net
0.0.0.0 alltopgirls.com
0.0.0.0 www.alltopgirls.com
0.0.0.0 bdsmlr.com
0.0.0.0 www.bdsmlr.com
0.0.0.0 elitebabes.com
0.0.0.0 www.elitebabes.com
0.0.0.0 eropics.org
0.0.0.0 www.eropics.org
0.0.0.0 layered-nylons.com
0.0.0.0 www.layered-nylons.com
0.0.0.0 mature.eu
0.0.0.0 www.mature.eu
0.0.0.0 mature.nl
0.0.0.0 www.mature.nl
0.0.0.0 nudecollect.com
0.0.0.0 www.nudecollect.com
0.0.0.0 nuderoot.com
0.0.0.0 www.nuderoot.com
0.0.0.0 onlyallsites.com
0.0.0.0 www.onlyallsites.com
0.0.0.0 onlyfans.com
0.0.0.0 www.onlyfans.com
0.0.0.0 onlytease.com
0.0.0.0 www.onlytease.com
0.0.0.0 sweetsinner.com
0.0.0.0 www.sweetsinner.com
0.0.0.0 thenude.eu
0.0.0.0 www.thenude.eu
0.0.0.0 xtrans.org
0.0.0.0 www.xtrans.org
```

I have also sorted the file and removed duplicates and blank lines. To make it easier to review my changes I did this as separate commits.

I hope this may be of use to you. Please let me know if I have made any mistakes in doing this so that I can correct them as the process is new to me. Thank you.

### CODE REVIEW

**Comment by okrabiblestudy** [comment]
Thanks @spirillen 

> This one is dead
> 
> * `adultboard.net`

Ok I can remove that. Thank you.

> You forgot `ladieswhomunch.bdsmlr.com` (https://archive.mypdns.org/T3265)
> 

Isn't it best to block all *bdsmlr.com sites?

Please note I cannot access your mypdns links. I tried logging in with my GitHub account but was informed " Your account has been blocked. Please contact your GitLab administrator if you think this is an error."

> `layered-nylons.com` See all here: https://archive.mypdns.org/T1497
> 

As above, I cannot view that link.

> `nuderoot.com` parked (hijacked by godaddy)

I can remove this.

> 
> `onlyallsites.com`: https://archive.mypdns.org/T1487
> 
> `onlytease.com`: https://archive.mypdns.org/T1486

Ditto.

> 
> `xtrans.org` Seems useless as it redirects to `http://www.entyhelwa.com/`
> 
> ```
> curl -I 'http://www.entyhelwa.com/'
> HTTP/1.1 301 Moved Permanently
> Location: https://www.entyhelwa.com/
> ```

Interesting. I can drop this one too.

If I may ask, what is the relationship between your mypdns service and this list? Are you using the Sinfonietta / hostfiles as part of the mypdns  service?

**Comment by spirillen** [comment]
Hey @okrabiblestudy 

> Please note I cannot access your mypdns links. I tried logging in with my GitHub account but was informed " Your account has been blocked. Please contact your GitLab administrator if you think this is an error."

Thanks for notifying me, it turns out I had miss configured my OmniAuth (https://docs.gitlab.com/ee/integration/omniauth.html#initial-omniauth-configuration) and trust me, there is a lot of funny things to touch :smiling_imp: 

But as I said to @molink36 in https://github.com/Clefspeare13/pornhosts/issues/363 please retry and let me know if anything goes wrong. It is after all a pretty new installation to take over for my beloved phabricator (now archive.mypdns.org)

But I've just tested something....

image


Hmm `https://arcive.mypdns.org/` is redirecting to `https://mypdns.org/` after login attempt....

image

**Comment by spirillen** [comment]
OK, it was the old Oauth2 url for https://archive.mypdns.org/, that is fixed now.

Login through Github
image

**Comment by Sinfonietta** [comment]
Thank you @okrabiblestudy merging.

**Pull request merged**
