### PR TITLE
Add another site

### PR DESCRIPTION
**Pull request by fabianski7**

### CODE REVIEW

**Review by spirillen — CHANGES_REQUESTED** [review]
This have been public blacklisted by at least two other projects and you should not add the www.$domain as it is redirecting

@mypdns

```
mypdns/my-privacy-dns/porn-records$ git blame submit_here/adult.mypdns.cloud/wildcard.list | grep 'porntn.com'
Blaming lines: 100% (3042/3042), done.
2b591c92e0 submit_here/adult.mypdns.cloud/wildcard.list (Spirillen      2021-07-20 15:09:36 +0200 2101) porntn.com
```

@clefspeare13/pornhosts
```shell
clefspeare13/pornhosts$ git blame submit_here/hosts.txt | grep 'porntn.com'
Blaming lines: 100% (15837/15837), done.
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  7895) porntn.com
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  9344) vcdn10.porntn.com
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  9353) vcdn5.porntn.com
```

**Comment by fabianski7** [comment]
> This have been public blacklisted by at least two other projects 

I am proposing to add to this list because it is included in StevenBlack's list and this domain is not being blocked.

> and you should not add the www.$domain as it is redirecting

the site admin can change this when he wants to. so I thought it best to include.

**Comment by spirillen** [comment]
If that is the case then script developed by other for steven is broken....

The domain was added the 20th of July 2021 as you can see with blame

```
git blame submit_here/hosts.txt | grep 'porntn\.com$'
Blaming lines: 100% (15841/15841), done.
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  7896) porntn.com
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  9345) vcdn10.porntn.com
f78e80961 (Spirillen 2021-07-20 15:09:51 +0200  9354) vcdn5.porntn.com
```

https://github.com/Clefspeare13/pornhosts/blob/c32876304b1668719c812e9973f3b2275485f988/download_here/0.0.0.0/hosts#L9582

https://github.com/Clefspeare13/pornhosts/blob/c32876304b1668719c812e9973f3b2275485f988/download_here/0.0.0.0/hosts#L11781-L11782

You'll have to open a issue with that third party list for support on that

and if you compare the lists even just by line numbers you'll notice a difference on roughly 500 lines

A little note: This is not an attempt to not get the records into this lists, it's sharing knowledge, and I don't see any reason for adding things twice.

For your comment about the www. I'm doesn't disagree with you, but you'll need to consider the size of the hosts files, I will there recommen you to view these posts
- https://github.com/Clefspeare13/pornhosts/issues/12
- https://mypdns.org/mypdns/support/-/wikis/DNS-Hosts#hosts-file-vs-unbound-test

**Comment by Sinfonietta** [comment]
Thankyou @fabianski7 I am merging this now.

**Pull request merged**
